### ISSUE TITLE
Icons aren't clear / understandable

### ISSUE THREAD

**Issue by tyu268** [yanqiangyu/Games#14]
Specifically:
* Power icon is used to restart game?
* Connection in corner has no meaningful affordances to tell you what it's for
* Nice to know that the corner button can be "demo" or "autoplay" (bot)

Possible solutions:
* Tooltips on hover or click
* Better iconography

**Comment by yanqiangyu** [comment]
Need to think about this one hard.

**Comment by yanqiangyu** [comment]
Did my best.
